services:
  webapp:
    build:
      context: ./webapp
      args:
        VITE_API_BASE_URL: "http://localhost:8000"
    ports:
      - "3000:80"
    volumes:
      - ./webapp:/app
    depends_on:
      - api
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 32M

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    volumes:
      - ./api:/app
    depends_on:
      - redis
      - mongo
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    deploy:
      resources:
        limits:
          memory: 384M

  redis:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - "--appendonly yes"
      - "--maxmemory 64mb"
      - "--maxmemory-policy allkeys-lru"
    deploy:
      resources:
        limits:
          memory: 64M

  mongo:
    image: mongo:4.0
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: ["mongod", "--quiet"]
    deploy:
      resources:
        limits:
          memory: 384M

volumes:
  redis_data:
  mongo_data:
